[package]
name = "twqrmap-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twmap = "0.9.0"
qrcode-generator = "4.1.6"
ndarray = "0.15.6"
clap = { version = "4.0", features = ["derive"] }